import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Logo from "./components/Logo";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto max-w-6xl px-4 md:px-6">
          <header className="flex items-center bg-white py-5 md:py-6 pl-5">
            <Logo />
          </header>
          <main className="pt-6 pb-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
