# Generated by Django 5.0.7 on 2024-08-03 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('tag', models.CharField(blank=True, max_length=200, null=True)),
                ('members_count', models.IntegerField(blank=True, null=True)),
                ('leader_name', models.CharField(blank=True, max_length=200, null=True)),
                ('leader_id', models.IntegerField(blank=True, null=True)),
                ('last_fetch', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('nation', models.CharField(max_length=200)),
                ('is_premium', models.BooleanField(default=False)),
                ('ship_type', models.CharField(max_length=200)),
                ('tier', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('total_battles', models.IntegerField(blank=True, null=True)),
                ('pvp_battles', models.IntegerField(blank=True, null=True)),
                ('pvp_wins', models.IntegerField(blank=True, null=True)),
                ('pvp_losses', models.IntegerField(blank=True, null=True)),
                ('pvp_ratio', models.FloatField(blank=True, null=True)),
                ('pvp_survival_rate', models.FloatField(blank=True, null=True)),
                ('wins_survival_rate', models.FloatField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('days_since_last_battle', models.IntegerField(blank=True, null=True)),
                ('last_battle_date', models.DateField(blank=True, null=True)),
                ('recent_games', models.JSONField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('stats_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_fetch', models.DateTimeField(blank=True, null=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warships.clan')),
            ],
        ),
        migrations.CreateModel(
            name='RecentLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warships.player')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('battles', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('survived_battles', models.IntegerField(blank=True, null=True)),
                ('battle_type', models.CharField(blank=True, max_length=200, null=True)),
                ('last_fetch', models.DateTimeField(blank=True, null=True)),
                ('interval_battles', models.IntegerField(blank=True, null=True)),
                ('interval_wins', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warships.player')),
            ],
        ),
    ]
