# Generated by Django 5.0.8 on 2024-08-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_lookup',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RecentLookup',
        ),
    ]
