# Generated by Django 5.0.8 on 2024-08-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0002_player_last_lookup_delete_recentlookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='ship_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
