# Generated by Django 5.0.8 on 2024-08-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0003_alter_ship_ship_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='recent_games',
            new_name='battles_json',
        ),
    ]
