# Generated by Django 5.0.8 on 2024-08-15 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0004_rename_recent_games_player_battles_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='members_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='days_since_last_battle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='pvp_battles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='pvp_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='pvp_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_battles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='battles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='survived_battles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
