# Generated by Django 5.0.8 on 2024-08-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0005_alter_clan_members_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(),
        ),
    ]
