# Generated by Django 5.0.8 on 2024-08-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0006_alter_player_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tiers_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
