# Generated by Django 5.0.8 on 2024-08-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0007_player_tiers_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='last_fetch',
        ),
        migrations.RemoveField(
            model_name='player',
            name='stats_updated_at',
        ),
        migrations.AddField(
            model_name='player',
            name='battles_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tiers_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
