# Generated by Django 5.0.8 on 2024-08-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0008_remove_player_last_fetch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tiers_updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='snapshot',
            unique_together={('player', 'date')},
        ),
    ]
