# Generated by Django 5.0.8 on 2024-08-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0009_remove_player_tiers_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
