# Generated by Django 5.0.8 on 2024-08-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0010_clan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_fetch',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
