# Generated by Django 5.0.8 on 2024-08-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0011_player_last_fetch'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='activity_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='randoms_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ships_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
