# Generated by Django 5.0.8 on 2024-08-18 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0012_player_activity_json_player_randoms_json_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='ships_json',
            new_name='type_json',
        ),
    ]
