# Generated by Django 5.0.8 on 2024-08-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0013_rename_ships_json_player_type_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='activity_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='randoms_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tiers_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='type_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
