# Generated by Django 5.0.8 on 2026-03-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0014_player_activity_updated_at_player_randoms_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ranked_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ranked_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
