# Generated by Django 5.0.8 on 2026-03-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0015_player_ranked_json_player_ranked_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='last_lookup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
