# Generated by Django 5.0.8 on 2026-03-09 17:05

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0016_add_clan_last_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_hidden', 'last_battle_date'], name='player_hidden_battle_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['last_lookup'], name='player_last_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['clan', 'last_battle_date'], name='player_clan_battle_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['pvp_battles', 'pvp_ratio'], name='player_battles_ratio_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['pvp_battles', 'pvp_survival_rate'], name='player_battles_surv_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='player_name_lower_idx'),
        ),
        migrations.AddIndex(
            model_name='clan',
            index=models.Index(fields=['last_lookup'], name='clan_last_lookup_idx'),
        ),
    ]