# Generated by Django 5.0.8 on 2026-03-09 17:55

from django.db import migrations


def add_trigram_index(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    schema_editor.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    schema_editor.execute(
        """
        CREATE INDEX IF NOT EXISTS player_name_trgm_idx
        ON warships_player
        USING gin (name gin_trgm_ops)
        WHERE name <> ''
        """
    )


def drop_trigram_index(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    schema_editor.execute('DROP INDEX IF EXISTS player_name_trgm_idx')


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0018_playerexplorersummary'),
    ]

    operations = [
        migrations.RunPython(
            add_trigram_index, reverse_code=drop_trigram_index),
    ]
