# Generated by Django 5.1.15 on 2026-03-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0021_merge_0020_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='verdict',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
