# Generated by Django 5.1.15 on 2026-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0022_player_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerexplorersummary',
            name='player_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
