# Generated by Django 5.1.15 on 2026-03-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warships', '0028_playerexplorersummary_efficiency_rank_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityVisitDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entity_type', models.CharField(choices=[('player', 'Player'), ('clan', 'Clan')], max_length=16)),
                ('entity_id', models.IntegerField()),
                ('entity_name_snapshot', models.CharField(max_length=200)),
                ('views_raw', models.IntegerField(default=0)),
                ('views_deduped', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('unique_sessions', models.IntegerField(default=0)),
                ('last_view_at', models.DateTimeField(blank=True, null=True)),
                ('source_first_party_views', models.IntegerField(default=0)),
                ('source_ga4_views', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'date'], name='visit_daily_type_date_idx'), models.Index(fields=['entity_type', 'entity_id', 'date'], name='visit_daily_entity_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'entity_type', 'entity_id'), name='unique_entity_visit_daily')],
            },
        ),
        migrations.CreateModel(
            name='EntityVisitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uuid', models.UUIDField(unique=True)),
                ('occurred_at', models.DateTimeField()),
                ('event_date', models.DateField(db_index=True)),
                ('entity_type', models.CharField(choices=[('player', 'Player'), ('clan', 'Clan')], max_length=16)),
                ('entity_id', models.IntegerField()),
                ('entity_name_snapshot', models.CharField(max_length=200)),
                ('entity_slug_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('route_path', models.CharField(max_length=255)),
                ('referrer_path', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('web_first_party', 'Web First Party'), ('ga4', 'Google Analytics 4')], default='web_first_party', max_length=32)),
                ('visitor_key_hash', models.CharField(max_length=64)),
                ('session_key_hash', models.CharField(max_length=64)),
                ('dedupe_bucket_started_at', models.DateTimeField(blank=True, null=True)),
                ('counted_in_deduped_views', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'event_date'], name='visit_event_entity_day_idx'), models.Index(fields=['entity_type', 'entity_id', 'occurred_at'], name='visit_event_entity_time_idx'), models.Index(fields=['entity_type', 'entity_id', 'visitor_key_hash', 'occurred_at'], name='visit_event_dedupe_idx')],
            },
        ),
    ]
